<?php
function searchForm($post=array()){
	$CI =& get_instance();
	$CI->make->sForm();
		$CI->make->sDivRow();
			$CI->make->sDivCol(6);
				$CI->make->input('Ref #','trans_ref',null,null);
			$CI->make->eDivCol();
			$CI->make->sDivCol(6);
				$CI->make->input('Email','email',null,null);
			$CI->make->eDivCol();
    	$CI->make->eDivRow();
	$CI->make->eForm();
	return $CI->make->code();
}
function redeemForm($email,$name,$points,$cart=array()){
	$CI =& get_instance();
	$CI->make->sForm('redeem/process',array('id'=>'redeem_form'));
		$CI->make->sDivRow();
			$CI->make->sDivCol(4);
				$CI->make->input('Email','email',$email,null,array('readonly'=>''),fa('fa-envelope') );
				//$CI->make->select('Email','email',$emails,null,array('class'=>'rOkay','ro-msg'=>'Select Email Address'),fa('fa-envelope'));
			$CI->make->eDivCol();
			$CI->make->sDivCol(4,'left');
				$CI->make->input('Name','name',$name['entry_name'],null,array('readonly'=>''),fa('fa-user') );
			$CI->make->eDivCol();
			$CI->make->sDivCol(4,'left');
				$CI->make->input('Location','location',$name['company_name'].', '.$name['area_name'],null,array('readonly'=>''),fa('fa-dot-circle-o') );
			$CI->make->eDivCol();
			$CI->make->sDivCol(4,'left');
				$CI->make->number('Current Points','curr_points',$points,null,array('readonly'=>''),fa('fa-dot-circle-o'));
			$CI->make->eDivCol();
    	$CI->make->eDivRow();
		$CI->make->sDivRow();
			$CI->make->sDivCol(12);
				$CI->make->sTable(array('class'=>'table form-tbl','id'=>'items-tbl'));
					$CI->make->sTableHead();
						$CI->make->sRow();
							$CI->make->th('Item',array('style'=>'width:35%;'));
							$CI->make->th('Points');
							$CI->make->th('Qty',array('style'=>'width:10%;'));
							$CI->make->th('',array('style'=>'width:100px'));
						$CI->make->eRow();
					$CI->make->eTableHead();
					$CI->make->sTableBody();
						$CI->make->sRow(array('id'=>'adds-row','style'=>'display:none;'));
							$CI->make->sTd();
								$CI->make->redeemItemsDrop(null,'item');
							$CI->make->eTd();
							$CI->make->sTd();
								$CI->make->span('',array('id'=>'points-txt'));
								$CI->make->hidden('points','');
							$CI->make->eTd();
							$CI->make->sTd();
								$CI->make->input(null,'qty');
							$CI->make->eTd();
							$CI->make->sTd(array('id'=>'btns-cell'));
							$CI->make->eTd();
						$CI->make->eRow();
							foreach ($cart as $id => $val) {
								$CI->make->sRow(array('class'=>'wagon-edit-rows','ref'=>$id,'cart'=>'redeem_cart'));
									$CI->make->sTd();
										$CI->make->append($val['item_name']);
									$CI->make->eTd();
									$CI->make->sTd();
										$CI->make->append($val['points']);
										// $CI->make->span('',array('id'=>'points-txt'));
										// $CI->make->hidden('points','');
									$CI->make->eTd();
									$CI->make->sTd();
										$CI->make->append($val['qty']);
									$CI->make->eTd();
									$CI->make->sTd();
									$CI->make->eTd();
								$CI->make->eRow();
							}
						$CI->make->sRow(array('class'=>'form-tbl-foot'));
							$CI->make->sTd(array('style'=>'text-align:right'));
								$CI->make->span('Total Points');
							$CI->make->eTd();
							$CI->make->sTd();
								$CI->make->span(num(0),array('id'=>'total-points'));
								$CI->make->span('Total Qty',array('class'=>'pull-right'));
							$CI->make->eTd();
							$CI->make->sTd();
								$CI->make->span(num(0),array('id'=>'total-qtys'));
							$CI->make->eTd();
							$CI->make->sTd();
							$CI->make->eTd();
						$CI->make->eRow();
					$CI->make->eTableBody();
				$CI->make->eTable();
			$CI->make->eDivCol();
    	$CI->make->eDivRow();
    	$CI->make->sDivRow();
    	    $CI->make->sDivCol(12,'right');
    	        $CI->make->button(fa('fa-check')." Redeem Items",array('id'=>'save-btn','style'=>'margin-right:10px;'),'success');
    	    $CI->make->eDivCol();
    	$CI->make->eDivRow();
	$CI->make->eForm();
	return $CI->make->code();
}
?>